"""Tests for pipeline/enrich.py — note enrichment via re-extraction and LLM update plan."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from pipeline.config import Config
from pipeline.enrich import _build_update_plan_prompt, enrich_note
from pipeline.extract import ExtractionError
from pipeline.models import ExtractedSource


# ─── Fixtures ───────────────────────────────────────────────────────────────


@pytest.fixture
def cfg(tmp_path: Path) -> Config:
    """Minimal Config rooted in a temporary directory."""
    for d in [
        "04-Wiki/entries",
        "04-Wiki/concepts",
        "04-Wiki/mocs",
        "04-Wiki/sources",
        "06-Config",
        "Meta/Scripts",
    ]:
        (tmp_path / d).mkdir(parents=True, exist_ok=True)
    return Config(vault_path=tmp_path)


@pytest.fixture
def mock_client() -> MagicMock:
    """Mock LLM client with a predictable generate() response."""
    client = MagicMock()
    client.generate.return_value = "- Add section on new findings\n- Update publication date"
    return client


def _write_note(path: Path, title: str = "Test Note", source_url: str = "https://example.com/article") -> None:
    """Helper to write a markdown note with frontmatter containing a source URL."""
    path.write_text(
        f"---\ntitle: {title}\nsource: {source_url}\ntags:\n  - test\n---\n\n"
        f"# {title}\n\nSome existing body content.\n",
        encoding="utf-8",
    )


# ─── _build_update_plan_prompt ──────────────────────────────────────────────


class TestBuildUpdatePlanPrompt:
    def test_returns_string_with_diff_and_titles(self):
        diff = "--- a\n+++ b\n@@ -1 +1 @@\n-old line\n+new line"
        result = _build_update_plan_prompt(diff, "Old Title", "New Title")

        assert isinstance(result, str)
        assert "Old Title" in result
        assert "New Title" in result
        assert "-old line" in result
        assert "+new line" in result
        assert "Update Plan:" in result

    def test_contains_curator_instructions(self):
        result = _build_update_plan_prompt("some diff", "A", "B")

        assert "knowledge curator" in result
        assert "No substantive changes" in result
        assert "20 bullets" in result

    def test_diff_truncated_to_8000_chars(self):
        long_diff = "x" * 10000
        result = _build_update_plan_prompt(long_diff, "T1", "T2")

        # The diff inside the prompt should be at most 8000 chars of the original
        assert "x" * 8000 in result
        assert "x" * 8001 not in result

    def test_empty_diff(self):
        result = _build_update_plan_prompt("", "Title A", "Title B")

        assert isinstance(result, str)
        assert "Title A" in result
        assert "Title B" in result

    def test_special_characters_in_titles(self):
        result = _build_update_plan_prompt("diff", "Title: \"Quoted\" & <Special>", "New {Title}")

        assert "\"Quoted\"" in result
        assert "<Special>" in result
        assert "{Title}" in result


# ─── enrich_note — happy path ───────────────────────────────────────────────


class TestEnrichNoteHappyPath:
    @patch("pipeline.enrich.extract_url")
    def test_plan_generated_and_written(self, mock_extract_url, tmp_path, cfg, mock_client):
        """Happy path: LLM returns a plan, sidecar file is written."""
        note = tmp_path / "test-note.md"
        _write_note(note)

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Updated Title",
            content="# Updated Title\n\nSome new body content with changes.\n",
        )

        result = enrich_note(note, cfg, write_plan=True, client=mock_client)

        assert result["status"] == "plan_generated"
        assert result["url"] == "https://example.com/article"
        assert result["diff_length"] > 0
        assert "plan" in result
        assert result["plan"] == mock_client.generate.return_value

        # Sidecar plan file should exist
        plan_path = Path(result["plan_path"])
        assert plan_path.exists()
        plan_content = plan_path.read_text(encoding="utf-8")
        assert "Update Plan" in plan_content
        assert "Add section on new findings" in plan_content
        assert "Generated by pipeline enrich" in plan_content

    @patch("pipeline.enrich.extract_url")
    def test_write_plan_false_skips_sidecar(self, mock_extract_url, tmp_path, cfg, mock_client):
        """When write_plan=False, no sidecar file is created."""
        note = tmp_path / "test-note.md"
        _write_note(note)

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Updated Title",
            content="Changed body content.\n",
        )

        result = enrich_note(note, cfg, write_plan=False, client=mock_client)

        assert result["status"] == "plan_generated"
        assert "plan_path" not in result
        # No sidecar written
        sidecar = tmp_path / "test-note-update-plan.md"
        assert not sidecar.exists()

    @patch("pipeline.enrich.extract_url")
    def test_sidecar_filename_derived_from_note_name(self, mock_extract_url, tmp_path, cfg, mock_client):
        """Sidecar file is named {stem}-update-plan.md."""
        note = tmp_path / "my-article.md"
        _write_note(note, title="My Article")

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="My Article v2",
            content="New content for my article.\n",
        )

        result = enrich_note(note, cfg, write_plan=True, client=mock_client)

        assert result["plan_path"].endswith("my-article-update-plan.md")

    @patch("pipeline.enrich.extract_url")
    def test_llm_called_with_correct_timeout(self, mock_extract_url, tmp_path, cfg, mock_client):
        """The LLM generate call uses cfg.llm_timeout."""
        note = tmp_path / "test-note.md"
        _write_note(note)
        cfg.llm_timeout = 42

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Title",
            content="Different body.\n",
        )

        enrich_note(note, cfg, client=mock_client)

        mock_client.generate.assert_called_once()
        _, kwargs = mock_client.generate.call_args
        assert kwargs["timeout"] == 42


# ─── enrich_note — no source URL ────────────────────────────────────────────


class TestEnrichNoteMissingSourceURL:
    def test_no_source_url_in_frontmatter(self, tmp_path, cfg):
        """Returns error when no source/url/source_url key is in frontmatter."""
        note = tmp_path / "no-url.md"
        note.write_text(
            "---\ntitle: No URL Note\ntags:\n  - test\n---\n\nBody.\n",
            encoding="utf-8",
        )

        result = enrich_note(note, cfg)

        assert result["status"] == "error"
        assert "No source URL" in result["error"]

    def test_empty_source_url(self, tmp_path, cfg):
        """Returns error when source key exists but value is empty."""
        note = tmp_path / "empty-url.md"
        note.write_text(
            "---\ntitle: Empty URL\nsource: \"\"\n---\n\nBody.\n",
            encoding="utf-8",
        )

        result = enrich_note(note, cfg)

        assert result["status"] == "error"
        assert "No source URL" in result["error"]

    def test_url_key_also_checked(self, tmp_path, cfg, mock_client):
        """The 'url' frontmatter key is also accepted as source URL."""
        note = tmp_path / "url-key.md"
        note.write_text(
            "---\ntitle: URL Key Note\nurl: https://example.com/via-url\n---\n\nBody.\n",
            encoding="utf-8",
        )

        with patch("pipeline.enrich.extract_url") as mock_ext:
            mock_ext.return_value = ExtractedSource(
                url="https://example.com/via-url",
                title="Title",
                content="Different content.\n",
            )
            result = enrich_note(note, cfg, client=mock_client)

        assert result["status"] == "plan_generated"
        assert result["url"] == "https://example.com/via-url"

    def test_source_url_key_also_checked(self, tmp_path, cfg, mock_client):
        """The 'source_url' frontmatter key is also accepted."""
        note = tmp_path / "source-url-key.md"
        note.write_text(
            "---\ntitle: Source URL Key\nsource_url: https://example.com/via-source-url\n---\n\nBody.\n",
            encoding="utf-8",
        )

        with patch("pipeline.enrich.extract_url") as mock_ext:
            mock_ext.return_value = ExtractedSource(
                url="https://example.com/via-source-url",
                title="Title",
                content="Different content.\n",
            )
            result = enrich_note(note, cfg, client=mock_client)

        assert result["status"] == "plan_generated"
        assert result["url"] == "https://example.com/via-source-url"


# ─── enrich_note — no changes ───────────────────────────────────────────────


class TestEnrichNoteNoChanges:
    @patch("pipeline.enrich.extract_url")
    def test_identical_content_returns_no_changes(self, mock_extract_url, tmp_path, cfg):
        """When re-extracted content matches existing body, return no_changes."""
        note = tmp_path / "unchanged.md"
        body = "# Test Note\n\nSome existing body content."
        note.write_text(
            f"---\ntitle: Test Note\nsource: https://example.com/article\n---\n\n{body}\n",
            encoding="utf-8",
        )

        # extract_body returns everything after '---\n', including the leading
        # newline, so new_source.content must match that exactly.
        from pipeline.utils import extract_body
        existing_body = extract_body(note.read_text(encoding="utf-8"))

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Test Note",
            content=existing_body,
        )

        result = enrich_note(note, cfg)

        assert result["status"] == "no_changes"
        assert result["url"] == "https://example.com/article"
        assert "plan" not in result


# ─── enrich_note — extraction errors ────────────────────────────────────────


class TestEnrichNoteExtractionErrors:
    @patch("pipeline.enrich.extract_url")
    def test_extraction_error_returns_error_status(self, mock_extract_url, tmp_path, cfg):
        """ExtractionError from extract_url is caught and returned as error."""
        note = tmp_path / "fail-extract.md"
        _write_note(note)

        mock_extract_url.side_effect = ExtractionError("Connection timeout")

        result = enrich_note(note, cfg)

        assert result["status"] == "error"
        assert "Re-extraction failed" in result["error"]
        assert "Connection timeout" in result["error"]

    @patch("pipeline.enrich.extract_url")
    def test_empty_re_extraction_content(self, mock_extract_url, tmp_path, cfg):
        """When re-extraction returns empty content, return error."""
        note = tmp_path / "empty-content.md"
        _write_note(note)

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Title",
            content="",
        )

        result = enrich_note(note, cfg)

        assert result["status"] == "error"
        assert "empty content" in result["error"]


# ─── enrich_note — LLM failure ──────────────────────────────────────────────


class TestEnrichNoteLLMFailure:
    @patch("pipeline.enrich.extract_url")
    def test_llm_exception_propagates(self, mock_extract_url, tmp_path, cfg):
        """When the LLM client raises, the exception propagates (not caught in enrich)."""
        note = tmp_path / "llm-fail.md"
        _write_note(note)

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Title",
            content="Different body text for diff.\n",
        )

        failing_client = MagicMock()
        failing_client.generate.side_effect = RuntimeError("LLM service unavailable")

        with pytest.raises(RuntimeError, match="LLM service unavailable"):
            enrich_note(note, cfg, client=failing_client)


# ─── enrich_note — missing file ─────────────────────────────────────────────


class TestEnrichNoteMissingFile:
    def test_missing_note_raises_file_not_found(self, tmp_path, cfg):
        """Calling enrich_note with a nonexistent path raises FileNotFoundError."""
        missing = tmp_path / "does-not-exist.md"

        with pytest.raises(FileNotFoundError):
            enrich_note(missing, cfg)


# ─── enrich_note — frontmatter edge cases ───────────────────────────────────


class TestEnrichNoteFrontmatterEdgeCases:
    @patch("pipeline.enrich.extract_url")
    def test_source_url_with_surrounding_quotes(self, mock_extract_url, tmp_path, cfg, mock_client):
        """Quoted URL values in frontmatter are stripped correctly."""
        note = tmp_path / "quoted-url.md"
        note.write_text(
            '---\ntitle: Quoted\nsource: "https://example.com/quoted"\n---\n\nBody.\n',
            encoding="utf-8",
        )

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/quoted",
            title="Quoted",
            content="New body.\n",
        )

        result = enrich_note(note, cfg, client=mock_client)

        # extract_url should be called with the unquoted URL
        mock_extract_url.assert_called_once()
        call_url = mock_extract_url.call_args[0][0]
        assert call_url == "https://example.com/quoted"
        assert result["status"] == "plan_generated"

    @patch("pipeline.enrich.extract_url")
    def test_title_fallback_to_stem(self, mock_extract_url, tmp_path, cfg, mock_client):
        """When frontmatter has no title, note_path.stem is used in the prompt."""
        note = tmp_path / "no-title-note.md"
        note.write_text(
            "---\nsource: https://example.com/x\n---\n\nBody.\n",
            encoding="utf-8",
        )

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/x",
            title="New Title",
            content="Changed body.\n",
        )

        enrich_note(note, cfg, client=mock_client)

        # The prompt should contain the stem as existing title
        prompt_arg = mock_client.generate.call_args[0][0]
        assert "no-title-note" in prompt_arg

    def test_no_frontmatter_at_all(self, tmp_path, cfg):
        """A note with no YAML frontmatter returns error (no source URL)."""
        note = tmp_path / "bare.md"
        note.write_text("Just some plain text, no frontmatter.\n", encoding="utf-8")

        result = enrich_note(note, cfg)

        assert result["status"] == "error"
        assert "No source URL" in result["error"]


# ─── enrich_note — default client creation ──────────────────────────────────


class TestEnrichNoteDefaultClient:
    @patch("pipeline.enrich.get_llm_client")
    @patch("pipeline.enrich.extract_url")
    def test_creates_default_client_when_none_passed(self, mock_extract_url, mock_get_client, tmp_path, cfg):
        """When client=None, get_llm_client(cfg) is called to create one."""
        note = tmp_path / "default-client.md"
        _write_note(note)

        mock_extract_url.return_value = ExtractedSource(
            url="https://example.com/article",
            title="Title",
            content="Different body.\n",
        )

        default_client = MagicMock()
        default_client.generate.return_value = "- No substantive changes"
        mock_get_client.return_value = default_client

        result = enrich_note(note, cfg, client=None)

        mock_get_client.assert_called_once_with(cfg)
        assert result["status"] == "plan_generated"
