"""Note enrichment — re-extract source URL, diff against existing, propose updates.

Uses existing Stage 1 extraction and an LLM call to generate a structured
update plan from a unified diff.
"""

from __future__ import annotations

import difflib
import logging
from pathlib import Path

from pipeline.config import Config
from pipeline.extract import ExtractionError, extract_url
from pipeline.llm_client import get_llm_client
from pipeline.utils import extract_body, parse_frontmatter

log = logging.getLogger(__name__)


def _build_update_plan_prompt(diff: str, existing_title: str, new_title: str) -> str:
    """Build the LLM prompt for generating an update plan from a diff."""
    return f"""You are a knowledge curator. A source note has been re-extracted and compared to its existing version. Review the unified diff below and produce a concise "Update Plan" in markdown bullet format.

Instructions:
- List only concrete, high-value changes (add section X, remove claim Y, update date, merge duplicate bullets, etc).
- Do NOT include full text of sections unless the change is a single sentence.
- If the diff is tiny or only formatting, say "No substantive changes".
- Keep the plan under 20 bullets.

Existing title: {existing_title}
New title: {new_title}

--- Diff ---
{diff[:8000]}

Update Plan:"""


def enrich_note(
    note_path: Path,
    cfg: Config,
    write_plan: bool = True,
    client=None,
) -> dict:
    """Re-extract source URL, diff against existing body, propose updates.

    Args:
        note_path: Path to the markdown note.
        cfg: Pipeline configuration.
        write_plan: If True, writes the plan to a sidecar file.
        client: Optional LLMClient instance.

    Returns:
        Dict with keys: status, url, diff_length, plan, plan_path (optional).
    """
    content = note_path.read_text(encoding="utf-8", errors="replace")
    fm = parse_frontmatter(content)

    # Resolve source URL from frontmatter
    url = ""
    for key in ("source", "url", "source_url"):
        val = fm.get(key)
        if val:
            url = str(val).strip().strip('"').strip("'")
            break

    if not url:
        return {
            "status": "error",
            "error": f"No source URL found in frontmatter of {note_path.name}",
        }

    # Re-run Stage 1 extraction
    try:
        new_source = extract_url(url, cfg, store=None)
    except ExtractionError as exc:
        return {
            "status": "error",
            "error": f"Re-extraction failed for {url}: {exc}",
        }

    if not new_source.content:
        return {
            "status": "error",
            "error": f"Re-extraction returned empty content for {url}",
        }

    existing_body = extract_body(content)
    new_body = new_source.content

    # Unified diff
    diff_lines = list(difflib.unified_diff(
        existing_body.splitlines(),
        new_body.splitlines(),
        fromfile=f"{note_path.name} (existing)",
        tofile=f"{note_path.name} (new)",
        lineterm="",
    ))
    diff = "\n".join(diff_lines)

    if not diff.strip():
        return {"status": "no_changes", "url": url}

    # LLM update plan
    if client is None:
        client = get_llm_client(cfg)

    prompt = _build_update_plan_prompt(
        diff,
        fm.get("title", note_path.stem),
        new_source.title,
    )
    plan_text = client.generate(prompt, timeout=cfg.llm_timeout)

    result: dict = {
        "status": "plan_generated",
        "url": url,
        "diff_length": len(diff),
        "plan": plan_text,
    }

    if write_plan:
        plan_path = note_path.with_name(f"{note_path.stem}-update-plan.md")
        plan_path.write_text(
            f"<!-- Update Plan for {note_path.name} -->\n\n"
            f"# Update Plan\n\n"
            f"{plan_text}\n\n"
            f"---\n\n"
            f"*Generated by pipeline enrich*\n",
            encoding="utf-8",
        )
        result["plan_path"] = str(plan_path)

    return result
