"""Legacy Obsidian vault → OKF v0.1 migration.

The migration command scans an existing Obsidian-style vault (typically laid
out under ``<vault>/04-Wiki/``) and rewrites it in place to comply with OKF
v0.1:

* Wikilinks (``[[slug]]`` / ``[[slug|alias]]``) become standard markdown links.
* Inline ``^[citation]`` footnote-style citations are extracted to a
  ``# Citations`` section at the bottom of the page.
* Frontmatter gains a ``type`` field inferred from the containing directory.
* Obsidian-specific frontmatter keys (``aliases``, ``orphaned`` …) are removed.
* Legacy root ``index.md`` / ``MOC.md`` are deleted and replaced by per-directory
  ``index.md`` and a bundle-root ``index.md`` generated by
  :mod:`pipeline.okf_indexgen`.
* A ``log.md`` is (re)generated with a migration entry.

Use :func:`migrate_vault` directly or via the ``llmwiki migrate`` CLI command.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from pipeline.okf_indexgen import (
    generate_bundle_index,
    generate_directory_index,
    generate_log,
)
from pipeline.okf_markdown import (
    atomic_write,
    build_frontmatter,
    parse_frontmatter,
)
from pipeline.okf_models import LogEntry, OKFConceptType

__all__ = [
    "migrate_vault",
    "extract_wikilinks",
    "convert_wikilink_to_okf",
    "rewrite_wikilinks",
    "_infer_type_from_path",
    "_convert_inline_citations",
]

# ── Wikilink utilities (moved from okf_markdown) ────────────────────────

# Legacy wikilink: [[slug]] or [[slug|alias]].
_WIKILINK_RE = re.compile(r"\[\[([^\]\|]+)(?:\|([^\]]+))?\]\]")


def extract_wikilinks(body: str) -> list[tuple[str, str | None]]:
    """Extract legacy ``[[slug]]`` / ``[[slug|alias]]`` wikilinks from ``body``.

    Returns a list of ``(slug, alias)`` tuples where ``alias`` is ``None``
    when no alias was given.
    """
    return [(m.group(1).strip(), m.group(2).strip() if m.group(2) else None)
            for m in _WIKILINK_RE.finditer(body)]


def convert_wikilink_to_okf(
    slug: str, alias: str | None = None, directory: str = "concepts"
) -> str:
    """Convert a single wikilink target to an OKF markdown link.

    ``[[slug]]``      → ``[slug](/concepts/slug.md)``
    ``[[slug|alias]]`` → ``[alias](/concepts/slug.md)``
    """
    display = alias if alias else slug
    return f"[{display}](/{directory}/{slug}.md)"


def rewrite_wikilinks(body: str, directory: str = "concepts") -> str:
    """Replace every ``[[wikilink]]`` in ``body`` with an OKF markdown link."""
    def _replace(match: re.Match[str]) -> str:
        slug = match.group(1).strip()
        alias = match.group(2).strip() if match.group(2) else None
        return convert_wikilink_to_okf(slug, alias=alias, directory=directory)

    return _WIKILINK_RE.sub(_replace, body)

# Directory-name → OKFConceptType mapping.  Keyed on the *leaf* directory
# name so that ``04-Wiki/concepts/foo.md`` resolves to "Concept" etc.
_DIR_TYPE_MAP: dict[str, OKFConceptType] = {
    "concepts": OKFConceptType.CONCEPT,
    "entries": OKFConceptType.ENTRY,
    "mocs": OKFConceptType.MOC,
    "sources": OKFConceptType.SOURCE,
    "references": OKFConceptType.REFERENCE,
}

# Frontmatter keys that are Obsidian-specific and therefore dropped during
# migration (OKF v0.1 has no concept of aliases or orphan markers).
_DROP_FM_KEYS: tuple[str, ...] = ("aliases", "orphaned", "orphaned_reason")

# Inline footnote-style citation: ^[Some citation text]
# Matches a caret immediately followed by a bracketed span.  The span may
# contain anything except a newline.  We use a non-greedy match for the inner
# text and require the closing bracket so the regex is well-behaved.
_INLINE_CITATION_RE = re.compile(r"\^\[([^\]]+)\]")

# Reserved filenames that are skipped during the concept-file migration pass.
_RESERVED_NAMES: frozenset[str] = frozenset({"index.md", "log.md", "MOC.md"})


# ── Type inference ──────────────────────────────────────────────────────


def _infer_type_from_path(file_path: str | Path) -> str:
    """Infer the OKF concept ``type`` string from a file's directory name.

    The leaf directory name is matched against the known OKF directories
    (``concepts``, ``entries``, ``mocs``, ``sources``, ``references``).
    Unknown directories default to :attr:`OKFConceptType.CONCEPT`.

    Parameters
    ----------
    file_path:
        Path to a ``.md`` concept file.

    Returns
    -------
    str
        One of the :class:`OKFConceptType` values as a plain string.
    """
    parts = Path(file_path).parts
    # Use the immediate parent directory name (the leaf directory).
    dir_name = parts[-2] if len(parts) >= 2 else ""
    concept_type = _DIR_TYPE_MAP.get(dir_name, OKFConceptType.CONCEPT)
    return str(concept_type.value)


# ── Inline citation extraction ──────────────────────────────────────────


def _convert_inline_citations(body: str) -> tuple[str, list[str]]:
    """Extract inline ``^[citation]`` citations from ``body``.

    Each ``^[text]`` occurrence is replaced by a numeric superscript reference
    (``[^N]``) and the citation text is collected in order.  When the body
    already contains a ``# Citations`` section the citations are appended to
    it; otherwise a new section is created at the bottom.

    Parameters
    ----------
    body:
        Markdown body text (without frontmatter).

    Returns
    -------
    tuple[str, list[str]]
        ``(new_body, citations)`` where *citations* is the ordered list of
        extracted citation strings.  When no inline citations are found the
        body is returned unchanged and the list is empty.
    """
    citations: list[str] = []

    def _replace(match: re.Match[str]) -> str:
        text = match.group(1).strip()
        citations.append(text)
        n = len(citations)
        return f"[^{n}]"

    new_body = _INLINE_CITATION_RE.sub(_replace, body)

    if not citations:
        return new_body, citations

    # Build the Citations section lines.
    cite_lines = ["# Citations", ""]
    for idx, text in enumerate(citations, start=1):
        cite_lines.append(f"[^{idx}]: {text}")
    cite_block = "\n".join(cite_lines)

    # If the body already ends with a Citations section, append to it rather
    # than duplicating the header.  We look for a top-level "# Citations"
    # heading on its own line.
    cit_heading_re = re.compile(r"^# Citations\s*$", re.MULTILINE)
    existing = cit_heading_re.search(new_body)
    if existing:
        # Append the new footnotes before any trailing whitespace.
        new_body = new_body.rstrip() + "\n"
        for idx, text in enumerate(citations, start=1):
            new_body += f"[^{idx}]: {text}\n"
    else:
        new_body = new_body.rstrip() + "\n\n" + cite_block + "\n"

    return new_body, citations


# ── Helpers ─────────────────────────────────────────────────────────────


def _strip_obsidian_keys(fm: dict) -> tuple[dict, list[str]]:
    """Remove Obsidian-specific keys from ``fm`` in place.

    Returns ``(fm, removed_keys)`` where *removed_keys* lists the keys that
    were actually present and have been dropped.
    """
    removed: list[str] = []
    for key in _DROP_FM_KEYS:
        if key in fm:
            removed.append(key)
            del fm[key]
    return fm, removed


def _migrate_concept_file(
    md_path: Path,
    wiki_dir: Path,
    dry_run: bool,
) -> tuple[bool, int, int, list[str]]:
    """Migrate a single concept ``.md`` file.

    Returns ``(migrated, wikilinks_converted, citations_converted, errors)``.
    """
    errors: list[str] = []
    raw = md_path.read_text(encoding="utf-8")

    fm, body = parse_frontmatter(raw)
    has_frontmatter = raw.startswith("---\n")

    changed = False
    wikilinks_count = 0

    # ── (a) Add 'type' if missing ───────────────────────────────────────
    if not fm.get("type"):
        inferred = _infer_type_from_path(md_path)
        fm["type"] = inferred
        changed = True

    # ── (b) Rewrite wikilinks in the body ────────────────────────────────
    # Determine the directory name relative to the wiki root for link paths.
    rel_dir = md_path.parent.relative_to(wiki_dir)
    directory_name = rel_dir.name if str(rel_dir) != "." else "concepts"

    if "[[" in body:
        new_body = rewrite_wikilinks(body, directory=directory_name)
        if new_body != body:
            wikilinks_count = body.count("[[")
            body = new_body
            changed = True

    # ── (c) Remove aliases / orphaned / orphaned_reason ──────────────────
    fm, removed_keys = _strip_obsidian_keys(fm)
    if removed_keys:
        changed = True

    # ── (e) Convert inline citations ─────────────────────────────────────
    body, citations = _convert_inline_citations(body)
    if citations:
        changed = True

    # ── Rebuild the file content ────────────────────────────────────────
    if has_frontmatter:
        new_raw = build_frontmatter(fm) + "\n\n" + body
    else:
        # No frontmatter originally — build one now that we've added type.
        new_raw = build_frontmatter(fm) + "\n\n" + body
        changed = True

    if changed and not dry_run:
        try:
            atomic_write(md_path, new_raw)
        except OSError as exc:
            errors.append(f"{md_path}: {exc}")

    return changed, wikilinks_count, len(citations), errors


def _gather_directories(wiki_dir: Path) -> list[Path]:
    """Return immediate sub-directories of ``wiki_dir`` that contain .md files."""
    dirs: list[Path] = []
    if not wiki_dir.is_dir():
        return dirs
    for child in sorted(wiki_dir.iterdir(), key=lambda p: p.name.lower()):
        if child.is_dir() and not child.name.startswith("."):
            dirs.append(child)
    return dirs


# ── Main entry point ───────────────────────────────────────────────────


def migrate_vault(vault_dir: str | Path, dry_run: bool = False) -> dict:
    """Migrate a legacy Obsidian vault to OKF v0.1 format.

    Parameters
    ----------
    vault_dir:
        Path to the vault root.  The wiki content is expected under
        ``<vault_dir>/04-Wiki/``.  When ``04-Wiki`` does not exist the
        ``vault_dir`` itself is treated as the wiki root (useful for tests).
    dry_run:
        When ``True`` no files are written or deleted; the returned dict
        still reports what *would* change.

    Returns
    -------
    dict
        ``{
            files_migrated: int,
            wikilinks_converted: int,
            files_deleted: int,
            indexes_generated: int,
            log_created: bool,
            errors: list[str]
        }``
    """
    vault_path = Path(vault_dir)
    wiki_dir = vault_path / "04-Wiki"
    if not wiki_dir.is_dir():
        # Fall back to the vault_dir itself as the wiki root.
        wiki_dir = vault_path

    result: dict = {
        "files_migrated": 0,
        "wikilinks_converted": 0,
        "files_deleted": 0,
        "indexes_generated": 0,
        "log_created": False,
        "errors": [],
    }

    # ── Migrate concept files ────────────────────────────────────────────
    for md_path in sorted(wiki_dir.rglob("*.md"), key=lambda p: str(p)):
        if md_path.name in _RESERVED_NAMES:
            continue

        try:
            migrated, wl_count, _cit_count, errs = _migrate_concept_file(
                md_path, wiki_dir, dry_run,
            )
            result["files_migrated"] += 1 if migrated else 0
            result["wikilinks_converted"] += wl_count
            result["errors"].extend(errs)
        except Exception as exc:  # noqa: BLE001
            result["errors"].append(f"{md_path}: {exc}")

    # ── Delete old root index.md and MOC.md ─────────────────────────────
    for stale_name in ("index.md", "MOC.md"):
        stale = wiki_dir / stale_name
        if stale.exists():
            if not dry_run:
                try:
                    stale.unlink()
                except OSError as exc:
                    result["errors"].append(f"delete {stale}: {exc}")
            result["files_deleted"] += 1

    # ── Generate per-directory index.md ─────────────────────────────────
    for sub_dir in _gather_directories(wiki_dir):
        concept_files = [
            f for f in sub_dir.glob("*.md")
            if f.name not in {"index.md", "log.md", "MOC.md"}
        ]
        if not concept_files:
            continue
        index_content = generate_directory_index(sub_dir, concept_files)
        if not dry_run:
            try:
                atomic_write(sub_dir / "index.md", index_content)
            except OSError as exc:
                result["errors"].append(f"index {sub_dir}: {exc}")
        result["indexes_generated"] += 1

    # ── Generate bundle-root index.md ───────────────────────────────────
    bundle_index_content = generate_bundle_index(wiki_dir)
    if not dry_run:
        try:
            atomic_write(wiki_dir / "index.md", bundle_index_content)
        except OSError as exc:
            result["errors"].append(f"bundle index: {exc}")
    result["indexes_generated"] += 1

    # ── Generate log.md with a migration entry ──────────────────────────
    today = date.today().isoformat()
    migration_entry = LogEntry(
        date=today,
        action="migrated",
        concept_id="_bundle",
        description=(
            "Migrated legacy Obsidian vault to OKF v0.1 format: "
            f"{result['files_migrated']} files migrated, "
            f"{result['wikilinks_converted']} wikilinks converted, "
            f"{result['files_deleted']} old index/MOC files deleted."
        ),
    )
    log_content = generate_log([migration_entry])
    if not dry_run:
        try:
            atomic_write(wiki_dir / "log.md", log_content)
            result["log_created"] = True
        except OSError as exc:
            result["errors"].append(f"log: {exc}")
    else:
        result["log_created"] = True

    return result
